# Generated by Django 5.2 on 2025-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0002_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='logged_in_only',
            field=models.BooleanField(default=False, verbose_name='Только для авторизованных'),
        ),
    ]
