# Generated by Django 5.2 on 2025-05-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treemenu', '0003_menuitem_logged_in_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='guest_only',
            field=models.BooleanField(default=False, verbose_name='Только для гостей'),
        ),
    ]
